### ISSUE TITLE
Agent DVR keep exiting

### ISSUE THREAD

**Issue by krizso** [ispysoftware/agent-install-scripts#10]
For issues with AgentDVR itself please use the [Reddit Forum](https://www.reddit.com/r/ispyconnect/) - This repo is for issues with installing and starting Agent DVR.

I've succesfully installed AgentDVR into Raspberry Pi.
After that I couldn't connect to it via browser, and the syslog contains the following error messages.

**Feb 22 14:37:17 HomeBridge systemd[1]: AgentDVR.service: Main process exited, code=exited, status=137/n/a
Feb 22 14:37:17 HomeBridge systemd[1]: AgentDVR.service: Unit entered failed state.
Feb 22 14:37:17 HomeBridge systemd[1]: AgentDVR.service: Failed with result 'exit-code'.
Feb 22 14:37:21 HomeBridge systemd[1]: Started Session c10 of user pi.
Feb 22 14:37:22 HomeBridge systemd[1]: AgentDVR.service: Service hold-off time over, scheduling restart.
Feb 22 14:37:22 HomeBridge systemd[1]: Stopped AgentDVR.**

It is repeating because the system is trying to restart the service.
I couldn't find any solution for this.

Thank you!

Krisztian

**Comment by ispysoftware** [comment]
hello you'll need to run 
dotnet Agent.dll 
in the Agent folder and capture the output - most likely it's missing some dependency of libcvextern - check the troubleshooter in the userguide for guidance.

https://www.ispyconnect.com/userguide-agent-dvr.aspx#troubleshooting

"On Linux and Raspberry Pi your system may not have some required libraries installed and Agent may fail to start with an error like libcvextern.so could not be found. You will need to use [ldd](https://www.lifewire.com/find-shared-libraries-ldd-command-4017941) to find which libraries are missing. To do this, open a terminal window, change to the Agent directory and run ldd libcvextern.so (or whatever library is causing issues). The output should tell you which dependencies need to be installed. Please [let us know](https://www.ispyconnect.com/contact.aspx) what's needed and what operating system you are using so we can update our docs."
