### ISSUE TITLE
Install script fails on MacOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by webeditors** [ispysoftware/agent-install-scripts#11]
**Describe the bug**
On a Mac Mini running MacOS 10.14 (Mojave), the install script fails toward the end when it can't find the flac-1.3.4.tar.xz file on xiph.org or the mirror. Homebrew then complains curl is not installed (thinking this is a red herring, because curl certainly is installed); then it can't find libopenjp2.7. I assume the message about finding a service definition is because I've tried several times to do a full install in various locations, but this time around it was in the home folder.

**Information**
MacOS 10.14 Mojave on Mac Mini 2.5GHz Intel Core i5 16GB RAM

**Console output from installer**
==> Downloading https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
Trying a mirror...
==> Downloading https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.4.tar.xz
Error: ffmpeg@4: Failed to download resource "flac"
Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
Downloading https://ispyfiles.azureedge.net/downloads/Agent_OSX64_3_8_8_0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.2M  100 29.2M    0     0  16.0M      0  0:00:01  0:00:01 --:--:-- 16.0M
Warning - could not find libopenjp2.7
Found service definition in /Library/LaunchDaemons/com.ispy.agent.dvr.plist
To disable, run: sudo launchctl unload -w /Library/LaunchDaemons/com.ispy.agent.dvr.plist
Then delete the file /Library/LaunchDaemons/com.ispy.agent.dvr.plist

**If the install script completed successfully but Agent doesn't start and complains about a file not found**
Tried the suggested method to use `ldd libopenjp2.7`, but that gave the error `-bash: ldd: command not found`

Tried `LD_DEBUG=libs ./start_agent.sh` but gave the error `-bash: ./start_agent.sh: No such file or directory`

**Comment by ispysoftware** [comment]
probably intermittent - those downloads seem to be working now

**Comment by gczychi** [comment]
Same here:

```
$ brew upgrade
...
==> Upgrading 3 outdated packages:
rubberband 2.0.0 -> 2.0.2
ffmpeg 4.4.1_3 -> 5.0
flac 1.3.3 -> 1.3.4
==> Downloading https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
Trying a mirror...
==> Downloading https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.4.tar.xz
Error: flac: Failed to download resource "flac"
Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
==> Downloading https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
Trying a mirror...
==> Downloading https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.4.tar.xz
Error: rubberband: Failed to download resource "flac"
Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
==> Downloading https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
Trying a mirror...
==> Downloading https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.4.tar.xz
Error: ffmpeg: Failed to download resource "flac"
Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
```

Is there a solution?
Thanks,
Gary

**Comment by ispysoftware** [comment]
can you check if

https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.4.tar.xz


downloads in a browser - it's working here on windows - maybe there's
an SSL cert version error?

**Comment by gczychi** [comment]
Downloads perfectly fine in any browser on a Mac 10.14 Mojave.

**Comment by ispysoftware** [comment]
maybe it's because you are missing curl? do you have curl installed?

**Comment by gczychi** [comment]
Is installed and works ok:

$ curl icanhazip.com
19.59.128.…

**Comment by ispysoftware** [comment]
found a similar issue:
https://github.com/Homebrew/discussions/discussions/2357

try running:

 brew install curl ca-certificates

**Comment by gczychi** [comment]
That did the trick:

> 
> brew install curl ca-certificates
> 

- the problem only happens on 10.14 Mojave (10.15 Catalina is fine)
- this will install another (keg-only) version of curl that is being used by brew

Thanks a lot! Everything works fine now.
