### ISSUE TITLE
zlib-1.2.11.tar.gz is no longer accessible

### ISSUE THREAD

**Issue by sylar6725** [ispysoftware/agent-install-scripts#12]
**Describe the bug**
Building zlib - version 1.2.11 failed because https://www.zlib.net/zlib-1.2.11.tar.gz is no longer exists
version change to 1.2.12 (https://www.zlib.net/zlib-1.2.12.tar.gz)
I made the modifications in the local script and I tested, the script runs correctly

**Information**
- Debian
- 11
- 64 bit

**Console output from installer**
building zlib - version 1.2.11
=======================
Downloading https://www.zlib.net/zlib-1.2.11.tar.gz as zlib-1.2.11.tar.gz
... Done
Failed to extract zlib-1.2.11.tar.gz

**Comment by ispysoftware** [comment]
thanks, this has been updated
