### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by waparty** [ispysoftware/agent-install-scripts#16]
Error: Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml. I need FFMPEG v4 shared libraries like avutil.56
ZeroConf: ZeroConf Service Started
Error:    at CoreLogic.FFmpeg.Init()
   at CoreLogic.Threads.StartUp()
Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml. I need FFMPEG v4 shared libraries like avutil.56

**Comment by skachatj** [comment]
help centos7
[root@localhost ~]# ./start_agent.sh
Starting...
Using default media location
Creating temp path for opencv in /tmp/
Get com port list
Using default port (8090)
Local Server running on port 8090
H264 compatible version of ffmpeg is required to use H264 encoding. Switch to VP8 in settings if unable to record.
Accepting http connections at http://*:8090/
Access locally at http://192.168.1.5:8090
Agent (v4.0.0.0)
Log start
Process is 64 bit
Using WorkStation GC
Init Webrtc
Init FFmpeg
Looking for ffmpeg in /usr/local/lib
Not in there..
Looking for ffmpeg in system default
Not in there..
Error: Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml. I need FFMPEG v4 shared libraries like avutil.56
Error:    at CoreLogic.FFmpeg.Init()
   at CoreLogic.Threads.StartUp()
Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml. I need FFMPEG v4 shared libraries like avutil.56
Install FFMPEG (v4) using the terminal. Run sudo apt-get install ffmpeg
./start_agent.sh: line 11:  3829 Убито              dotnet AgentDVR/Agent.dll

**Comment by skachatj** [comment]
[root@localhost ~]# ffmpeg -version
ffmpeg version 3.4.10 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-44)
configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --disable-encoder=libopus --enable-libpulse --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100

**Comment by ispysoftware** [comment]
"I need FFMPEG v4 shared libraries like avutil.56"

**Comment by jgusta** [comment]
I'm having [a similar] issue. Here is a bit more of the output leading up to that error:

```shell
Starting AgentDVR
Starting...
Using default media location
Creating temp path for opencv in /var/folders/6f/xxxxxxxxx/T/
Get com port list
Using default port (8090)
Local Server running on port 8090
H264 compatible version of ffmpeg is required to use H264 encoding. Switch to VP8 in settings if unable to record.
Accepting http connections at http://*:8090/
Access locally at http://192.168.1.2:8090
Agent (v4.0.0.0)
Log start
Process is 64 bit
Using WorkStation GC
Init Webrtc
Init FFmpeg
Looking for ffmpeg in homebrew/lib
Not in there..
Looking for ffmpeg in /usr/local/lib
Not in there..
Looking for ffmpeg in system default
Not in there..
Error: Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml. I need FFMPEG v4 shared libraries like avutil.56
Error:    at CoreLogic.FFmpeg.Init()
   at CoreLogic.Threads.StartUp()
Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml. I need FFMPEG v4 shared libraries like avutil.56
Install FFMPEG (v4) using the terminal. Install homebrew then run 'brew install ffmpeg@4'
```
You can see in a couple places in the output that it is using my system installed ffmpeg (v5) rather than the versioned one. I know v4 is been installed (the script took about 7 hours to compile) but it doesn't seem to find it when it's done.

Is the agent looking for `${ABSOLUTE_PATH}/AgentDVR/homebrew/opt/ffmpeg@4/lib`? `avutil` is in there, however the agent doesn't seem to find it.

Thanks

**Comment by ispysoftware** [comment]
you can add a path to the ffmpeg libraries by editing the media/xml/confix.xml file and adding it to the (beginning of) the FFMPEG_SEARCH  entry
