### ISSUE TITLE
Request: Support Matrox MAX h.264 DSP & CompressHD pcie

### ISSUE THREAD

**Issue by juanpc2018** [ispysoftware/agent-install-scripts#18]
for Windows & Mac there are drivers for Matrox MXO2 MAX i/o and ComnpressHD PCIe,
those are ASIC or FPGA h.264 HW Encoders.

in OSX, when combined with GPU + CPU + MAX DSP,
in FinalCutPro + Compressor,

is very energy efficient, No Fan noise.

sadly No support for Linux.

----------------
$ lspci | grep -i Matrox
0a:00.0 Multimedia controller: Matrox Electronics Systems Ltd. Device 82d0

Device 82d0
Not here:
https://wiki.debian.org/DeviceDatabase/PCI

$ modinfo ​​
$ sudo modprobe ​​

MXO2
"MX Oxygen"
was a Pro PCIe capture device, still good enough today for HDMI 1080p30p
has a PCIe card, but can be used with Thunderbolt2 or ExpressCard34.

there was 2 versions available...
Standard: I/O Only,
different size configuration i/o, small mini basic, medium, battery powered portable, rackmount, pcie card mojito, pcie dsp only compresshd.

MAX version = includes aditional DSP ic that allows encoding h.264 video in HW, fast, silent, and power efficient.
No need for CPU fans spinning at 2000rpm for hours.

Matrox Max Caputre h.264 SW is better for Windows8.1, 10,
Ventura Capture for OSX only works in Yosemite 10.10 or older, never updated..
but Matrox MAX v4.6 drivers work upto OSX HighSierra 10.13.6
works up to FinalCutPro 1O.4.3 + Compressor 4.4.1
Adobe CS6 Encoder Pre-Mercury Engine..
FCP+Compressor+GPU acceleration+MAX DSP+CPU does encode faster & silent.

there is also Unofficial OSX drivers Non-MAX, that support QuickTime Apps.
https://vosaic.com/support/matrox-mx...s-for-yosemite
https://vosaic.com/support/matrox-mx...-for-mavericks
OBS, QuickTimePlayer Recorder, Zoom, FaceTime, etc...

Official drivers for OSX v4.6 do Not support QuickTime Apps, Only direct support: Avid, Adobe, etc...
There are MAX and Non-MAX drivers.

seems there is No Linux support.
OBS does Not detect.

https://www.youtube.com/results?sear...atrox+max+mxo2

OBS Recording
Encoder: FFMPEG VAAPI
VAAPI Device: Card0: /dev/dri/renderD128
VAAPI Codec: h.264

but thats intel cpu.
https://github.com/intel/intel-vaapi-driver
https://01.org/linuxmedia
https://wiki.archlinux.org/title/Har...o_acceleration
https://github.com/microsoft/WSL/issues/4700
https://forums.raspberrypi.com/viewt...?f=68&t=307392
[https://forums.raspberrypi.com/viewt...7392&p=1858265​](https://forums.raspberrypi.com/viewt...7392&p=1858265%E2%80%8B)

.
_______________________________________________
ffmpeg-devel mailing list
[ffmpeg-devel@ffmpeg.org](mailto:ffmpeg-devel@ffmpeg.org)
https://ffmpeg.org/mailman/listinfo/ffmpeg-devel

**Comment by ispysoftware** [comment]
I'm not sure what this is - is this a feature request, bug report or did you have something to add to the repo?
