### ISSUE TITLE
Failed pearOS 07.01 kernel 5.14.0-1036-oem

### ISSUE THREAD

**Issue by juanpc2018** [ispysoftware/agent-install-scripts#19]
installer:
https://archive.org/details/pearOS_Monterey_64bit-12-beta-2021.07.01

The New pearOS Nicec0re is a big change from Debian to Arch Linux, its raw/coarse...
pearOS Monterey 07.01 is the Peak of Debian Development, very nice.

Repo for NiceC0re Arch pearOS.
https://github.com/pearOS-archlinux/iso

i like it because has a time saving feature,
select multiple files, create a folder, type a name and moves all the files automatically inside the folder.

changed the kernel 5.10.1011, everything works.
with a few exceptions.

$ uname -a
Linux 5.14.0-1036-oem SMP Mon May 9 09:15:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ synaptic
search linux oem
installed

linux-buildinfo-5.14.0-1036-oem
linux-headers-5.14.0-1036-oem
linux-image-5.14.0-1036-oem
linux-modules-5.14.0-1036-oem
linux-oem-5.14-headers-5.14.0-1036
linux-oem-5.14-tools-5.14.0-1036
linux-tools-5.14.0-1036-oem

-----------

building libtiff - version 4.2.0

=======================
Downloading https://download.osgeo.org/libtiff/tiff-4.2.0.tar.gz as tiff-4.2.0.tar.gz
... Done
Extracted tiff-4.2.0.tar.gz
$ ./configure --prefix=/home/p/AgentDVR/ffmpeg-build/workspace --enable-shared --disable-static --disable-dependency-tracking --disable-lzma --disable-webp --disable-zstd --without-x
$ make -j 4
$ make install
Making install in port
make[1]: Entering directory '/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/port'
make[2]: Entering directory '/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/port'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/port'
make[1]: Leaving directory '/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/port'
Making install in libtiff
make[1]: Entering directory '/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/libtiff'
make[2]: Entering directory '/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/libtiff'
 /usr/bin/mkdir -p '/home/p/AgentDVR/ffmpeg-build/workspace/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libtiff.la libtiffxx.la '/home/p/AgentDVR/ffmpeg-build/workspace/lib'
libtool: install: /usr/bin/install -c .libs/libtiff.so.5.6.0 /home/p/AgentDVR/ffmpeg-build/workspace/lib/libtiff.so.5.6.0
libtool: install: (cd /home/p/AgentDVR/ffmpeg-build/workspace/lib && { ln -s -f libtiff.so.5.6.0 libtiff.so.5 || { rm -f libtiff.so.5 && ln -s libtiff.so.5.6.0 libtiff.so.5; }; })
libtool: install: (cd /home/p/AgentDVR/ffmpeg-build/workspace/lib && { ln -s -f libtiff.so.5.6.0 libtiff.so || { rm -f libtiff.so && ln -s libtiff.so.5.6.0 libtiff.so; }; })
libtool: install: /usr/bin/install -c .libs/libtiff.lai /home/p/AgentDVR/ffmpeg-build/workspace/lib/libtiff.la
libtool: warning: relinking 'libtiffxx.la'
libtool: install: (cd /home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/libtiff; /bin/bash "/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/libtool"  --tag CXX --mode=relink g++ -g -O2 -no-undefined -version-info 11:0:6 -o libtiffxx.la -rpath /home/p/AgentDVR/ffmpeg-build/workspace/lib tif_stream.lo ../libtiff/libtiff.la ../port/libport.la -ljbig -ljpeg -lz -lm )
libtool: relink: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o  .libs/tif_stream.o  -Wl,--whole-archive ../port/.libs/libport.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/home/p/AgentDVR/ffmpeg-build/workspace/lib -L/home/p/AgentDVR/ffmpeg-build/workspace/lib -ltiff -ljbig -ljpeg -lz -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o  -g -O2   -Wl,-soname -Wl,libtiffxx.so.5 -o .libs/libtiffxx.so.5.6.0
/usr/bin/ld: /home/p/AgentDVR/ffmpeg-build/workspace/lib/libz.a(deflate.o): relocation R_X86_64_PC32 against symbol `z_errmsg' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'libtiffxx.la' with the above command before installing it
make[2]: *** [Makefile:586: install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/libtiff'
make[1]: *** [Makefile:875: install-am] Error 2
make[1]: Leaving directory '/home/p/AgentDVR/ffmpeg-build/packages/tiff-4.2.0/libtiff'
make: *** [Makefile:543: install-recursive] Error 1

Failed to Execute make install
Adding permission for local device access
[sudo] password : 
The user `p' is already a member of `video'.
Found service definition in /etc/systemd/system/AgentDVR.service
Go to http://localhost:8090

**Console output from installer**
Please paste the output from the installer showing the error messages

**If the install script completed successfully but Agent doesn't start and complains about a file not found**
Change to the Agent DVR directory in terminal and run:

    ldd libcvextern.so (or whatever library is causing issues). 

The output should tell you which dependencies need to be installed.  Try installing these dependencies using (replace xxxx with the missing dependency name):

    sudo apt-get install xxxx

.. and update this report with the missing libraries.

If that doesn't resolve the issue start agent by calling:

LD_DEBUG=libs ./start_agent.sh

and attach the output to this ticket

**Additional context**

**Comment by juanpc2018** [comment]
~$ cd AgentDVR

~/AgentDVR$ ldd libtiff.so
ldd: ./libtiff.so: No such file or directory

~/AgentDVR$ ldd libtiff
ldd: ./libtiff: No such file or directory

~/AgentDVR$ ldd libtiffxx.la
ldd: ./libtiffxx.la: No such file or directory

~/AgentDVR$ ldd libtiff.la
ldd: ./libtiff.la: No such file or directory

**Comment by juanpc2018** [comment]
265822:     find library=liblibc.so.6.so [0]; searching                                               
    265822:      search path=/home/p/AgentDVR/ffmpeg-build/workspace/lib              (LD_LIBRARY_PATH) 
    265822:       trying file=/home/p/AgentDVR/ffmpeg-build/workspace/lib/liblibc.so.6.so               
    265822:      search cache=/etc/ld.so.cache                                                            
    265822:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)                                                                                        
    265822:       trying file=/lib/x86_64-linux-gnu/liblibc.so.6.so                                       
    265822:       trying file=/usr/lib/x86_64-linux-gnu/liblibc.so.6.so                                   
    265822:       trying file=/lib/liblibc.so.6.so                                                        
    265822:       trying file=/usr/lib/liblibc.so.6.so                                                    
    265822:                                                                                               
vdpau                                                                                                     
ZeroConf: ZeroConf Service Started                                                                        
cuda                                                                                                      
vaapi                                                                                                     
drm                                                                                                       
opencl                                                                                                    
Found 0 devices                                                                                           
call arecord -l                                                                                           
    265822:     find library=dl.so [0]; searching                                                         
    265822:      search path=/home/p/AgentDVR/ffmpeg-build/workspace/lib              (LD_LIBRARY_PATH) 
    265822:       trying file=/home/p/AgentDVR/ffmpeg-build/workspace/lib/dl.so                         
    265822:      search cache=/etc/ld.so.cache                                                            
    265822:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)                                                                                        
    265822:       trying file=/lib/x86_64-linux-gnu/dl.so                                                 
    265822:       trying file=/usr/lib/x86_64-linux-gnu/dl.so                                             
    265822:       trying file=/lib/dl.so                                                                  
    265822:       trying file=/usr/lib/dl.so                                                              
    265822:                                                                                               
    265822:     find library=libdl.so [0]; searching                                                      
    265822:      search path=/home/p/AgentDVR/ffmpeg-build/workspace/lib              (LD_LIBRARY_PATH) 
    265822:       trying file=/home/p/AgentDVR/ffmpeg-build/workspace/lib/libdl.so                      
    265822:      search cache=/etc/ld.so.cache                                                            
    265822:       trying file=/lib/x86_64-linux-gnu/libdl.so                                              
    265822:                                                                                               
    265822:                                                                                               
    265822:     calling init: /home/p/AgentDVR/libcvextern.so                                           
    265822:                                                                                               
    265822:     find library=cvextern.so [0]; searching                                                   
    265822:      search path=/home/p/AgentDVR/ffmpeg-build/workspace/lib              (LD_LIBRARY_PATH) 
    265822:       trying file=/home/p/AgentDVR/ffmpeg-build/workspace/lib/cvextern.so                   
    265822:      search cache=/etc/ld.so.cache                                                            
    265822:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)                                                                                        
    265822:       trying file=/lib/x86_64-linux-gnu/cvextern.so                                           
    265822:       trying file=/usr/lib/x86_64-linux-gnu/cvextern.so                                       
    265822:       trying file=/lib/cvextern.so                                                            
    265822:       trying file=/usr/lib/cvextern.so                                                        
    265822:                                                                                               
    265822:     find library=e_sqlite3.so [0]; searching                                                  
    265822:      search path=/home/p/AgentDVR/ffmpeg-build/workspace/lib              (LD_LIBRARY_PATH) 
    265822:       trying file=/home/p/AgentDVR/ffmpeg-build/workspace/lib/e_sqlite3.so                  
    265822:      search cache=/etc/ld.so.cache                                                            
    265822:      search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib              (system search path)                                                                                        
    265822:       trying file=/lib/x86_64-linux-gnu/e_sqlite3.so                                          
    265822:       trying file=/usr/lib/x86_64-linux-gnu/e_sqlite3.so                                      
    265822:       trying file=/lib/e_sqlite3.so                                                           
    265822:       trying file=/usr/lib/e_sqlite3.so                                                       
    265822:                                                                                               
    265822:                                                                                               
    265822:     calling init: /home/p/AgentDVR/libe_sqlite3.so                                          
    265822:                                                                                               
    265822:     /home/p/AgentDVR/libe_sqlite3.so: error: symbol lookup error: undefined symbol: sqlite3_win32_set_directory8 (fatal)                                                                              
Preloading Images                                                                                         
    265822:     /home/p/AgentDVR/.dotnet/shared/Microsoft.NETCore.App/3.1.4/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_EndsWithW (fatal)                   
Turn Server accepting connections at 192.168.0.131:3478 using range 50000-50010)                         
Failed to create a UDP socket bound at 0.0.0.0:3478                                                       
MQTT not configured or enabled                                                                            
Loaded 0 cameras and 0 mics from /home/p/AgentDVR/Media/XML/objects.xml                                 
Running at http://localhost:44869                                                                         
IP addresses:        
found 192.168.xxx.xxx
found 192.168.xxx.xxx
    265822:     find library=libnss_mdns4_minimal.so.2 [0]; searching
    265822:      search path=/home/p/AgentDVR/ffmpeg-build/workspace/lib              (LD_LIBRARY_PATH)
    265822:       trying file=/home/p/AgentDVR/ffmpeg-build/workspace/lib/libnss_mdns4_minimal.so.2
    265822:      search cache=/etc/ld.so.cache
    265822:       trying file=/lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
    265822:
    265822:
    265822:     calling init: /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
    265822:
    265822:     find library=libnss_dns.so.2 [0]; searching
    265822:      search path=/home/p/AgentDVR/ffmpeg-build/workspace/lib              (LD_LIBRARY_PATH)
    265822:       trying file=/home/p/AgentDVR/ffmpeg-build/workspace/lib/libnss_dns.so.2
    265822:      search cache=/etc/ld.so.cache
    265822:       trying file=/lib/x86_64-linux-gnu/libnss_dns.so.2
    265822:
    265822:
    265822:     calling init: /lib/x86_64-linux-gnu/libnss_dns.so.2
    265822:
    265822:     /home/p/AgentDVR/.dotnet/shared/Microsoft.NETCore.App/3.1.4/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_ToAsciiW (fatal)
    265822:     /home/p/AgentDVR/.dotnet/shared/Microsoft.NETCore.App/3.1.4/System.Globalization.Native.so: error: symbol lookup error: undefined symbol: GlobalizationNative_GetSortKeyW (fatal)

**Comment by juanpc2018** [comment]
~/AgentDVR$ ls
Agent                        
ja                                            
Microsoft.Extensions.ObjectPool.dll  
SQLitePCLRaw.provider.dynamic_cdecl.dll
Agent.deps.json                   
ko                                                 
Microsoft.Extensions.Options.dll    
SshNet.Security.Cryptography.dll
Agent.dll                              
KoenZomers.OneDrive.Api.dll                                
Microsoft.Extensions.Primitives.dll  
System.Drawing.Common.dll
Agent.dll.config                       
ibcvextern.so                                             
Microsoft.Win32.Registry.dll         
System.Formats.Asn1.dll
AgentDVR.service                       
libe_sqlite3.so                                            
Microsoft.Win32.SystemEvents.dll     
System.IO.Pipelines.dll
agent-register.sh                      
libjingle_peerconnection_so.so                             
MQTTnet.dll                          
System.IO.Ports.dll
agent-reset-local-login.sh             
libSkiaSharp.so                                            
NAudio.Asio.dll                      
System.Net.IPNetwork.dll
agent-reset.sh                         
libSystem.IO.Ports.Native.so                               
NAudio.Core.dll                      
System.Private.ServiceModel.dll
Agent.runtimeconfig.json               
LibVLCSharp.dll                                            
NAudio.dll                           
System.Reflection.DispatchProxy.dll
Commands                               
LitJSON.dll                                                
NAudio.Midi.dll                      
System.Security.AccessControl.dll
Common.Logging.Core.dll                
Makaretu.Dns.dll                                           
NAudio.Wasapi.dll                    
System.Security.Cryptography.Cng.dll
Common.Logging.dll                     
Makaretu.Dns.Multicast.dll                                 
NAudio.WinForms.dll                  
System.Security.Cryptography.Pkcs.dll
CoreLogic.dll                          
Masks                                                      
NAudio.WinMM.dll                     
System.Security.Cryptography.Xml.dll
CoreUpdater.dll                        
Media                                                      
Newtonsoft.Json.dll                  
System.Security.Permissions.dll
CoreUpdater.runtimeconfig.json         
Microsoft.AspNetCore.Connections.Abstractions.dll          
OnvifDiscovery.dll                   
System.Security.Principal.Windows.dll
cs                                     
Microsoft.AspNetCore.Http.Connections.Client.dll           
pl                                   
System.ServiceModel.dll
current_port.txt                       
Microsoft.AspNetCore.Http.Connections.Common.dll           
pt-BR                                
System.ServiceModel.Duplex.dll
de                                     
Microsoft.AspNetCore.Http.Features.dll                     
Renci.SshNet.dll                     
System.ServiceModel.Http.dll
DirectShowLib-2005.dll                 
Microsoft.AspNetCore.SignalR.Client.Core.dll               
RtspClientSharp.dll                  
System.ServiceModel.NetTcp.dll
Emgu.CV.Platform.NetStandard.dll       
Microsoft.AspNetCore.SignalR.Client.dll                    
ru                                   
System.ServiceModel.Primitives.dll
es                                     
Microsoft.AspNetCore.SignalR.Common.dll                    
SimpleBase.dll                       
System.ServiceModel.Security.dll
FFmpeg.AutoGen.dll                     
Microsoft.AspNetCore.SignalR.Protocols.Json.dll            
SixLabors.Fonts.dll                  
System.Threading.Channels.dll
ffmpeg-build                           
Microsoft.Bcl.AsyncInterfaces.dll                          
SixLabors.ImageSharp.dll             
System.Windows.Extensions.dll
fr                                     
Microsoft.Extensions.Configuration.Abstractions.dll        
SixLabors.ImageSharp.Drawing.dll     
Tmds.LibC.dll
Google.Apis.Auth.dll                   
Microsoft.Extensions.Configuration.Binder.dll              
SkiaSharp.dll                        tr
Google.Apis.Auth.PlatformServices.dll  
Microsoft.Extensions.Configuration.dll                     
sounds                               
webrtc.dll
Google.Apis.Core.dll                   
Microsoft.Extensions.DependencyInjection.Abstractions.dll  
SQLite-net.dll                       
XML
Google.Apis.dll                        
Microsoft.Extensions.DependencyInjection.dll               
SQLitePCLRaw.batteries_v2.dll        
zh-Hans
Google.Apis.Drive.v3.dll               
Microsoft.Extensions.Logging.Abstractions.dll              
SQLitePCLRaw.core.dll                
zh-Hant
it                                     
Microsoft.Extensions.Logging.dll                           
SQLitePCLRaw.nativelibrary.dll

**Comment by ispysoftware** [comment]
This looks like a compatibility issue with the dotnet runtime on this linux version.

Possible workaround here:
https://stackoverflow.com/questions/67433905/how-to-resolve-symbol-lookup-error-on-net-core-on-linux
