### ISSUE TITLE
Debian 8

### ISSUE THREAD

**Issue by djdoubleg** [ispysoftware/agent-install-scripts#2]
**Describe the bug**
A clear and concise description of what the bug is. For issues with Agent DVR itself please use the [Reddit Forum](https://www.reddit.com/r/ispyconnect/) - This repo is for issues with installing and starting Agent DVR.

**Information**
- Debian
- 8 Jessie
- 64bit

**Console output from installer**
root@nas:~# bash <(curl -s "https://raw.githubusercontent.com/ispysoftware/agent                                                                                                                                                             -install-scripts/main/install.sh")
/dev/fd/62: line 6: /etc/lsb-release: No such file or directory
installing build tools
Ign file:  InRelease
Ign file:  Release.gpg
Ign file:  Release
Ign http://ftp.hu.debian.org jessie InRelease
Hit http://ftp.hu.debian.org jessie-updates InRelease
Hit http://security.debian.org jessie/updates InRelease
Hit http://security.debian.org jessie/updates InRelease
Hit http://linux-packages.resilio.com resilio-sync InRelease
Hit http://archive.debian.org jessie-backports InRelease
Hit https://download.docker.com jessie InRelease
Hit http://dl.google.com stable InRelease
Get:1 http://packages.ivideon.com stable InRelease [5,933 B]
Hit http://download.virtualbox.org jessie InRelease
Hit http://apt.syncthing.net syncthing InRelease
Hit http://packages.openmediavault.org erasmus InRelease
Hit https://openmediavault.github.io erasmus InRelease
Hit https://packages.microsoft.com stretch InRelease
Ign file:  Translation-en_US
Ign file:  Translation-en
Get:2 http://ftp.hu.debian.org jessie Release.gpg [1,652 B]
Hit http://ftp.hu.debian.org jessie Release
Hit http://ftp.hu.debian.org jessie-updates/main Sources
Hit http://ftp.hu.debian.org jessie-updates/contrib Sources
Hit http://ftp.hu.debian.org jessie-updates/non-free Sources
Hit http://ftp.hu.debian.org jessie-updates/main amd64 Packages
Hit http://ftp.hu.debian.org jessie-updates/contrib amd64 Packages
Hit http://ftp.hu.debian.org jessie-updates/non-free amd64 Packages
Hit http://ftp.hu.debian.org jessie-updates/contrib Translation-en
Hit http://ftp.hu.debian.org jessie-updates/main Translation-en
Hit http://ftp.hu.debian.org jessie-updates/non-free Translation-en
Get:3 http://security.debian.org jessie/updates/main Sources [366 kB]
Get:4 http://security.debian.org jessie/updates/contrib Sources [1,439 B]
Get:5 http://security.debian.org jessie/updates/non-free Sources [1,915 B]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [781 kB]
Get:7 http://linux-packages.resilio.com resilio-sync/non-free amd64 Packages [48                                                                                                                                                             2 B]
Get:8 http://security.debian.org jessie/updates/contrib amd64 Packages [2,506 B]
Get:9 http://security.debian.org jessie/updates/non-free amd64 Packages [4,702 B                                                                                                                                                             ]
Get:10 http://security.debian.org jessie/updates/contrib Translation-en [1,211 B                                                                                                                                                             ]
Get:11 http://security.debian.org jessie/updates/main Translation-en [401 kB]
E: Release file for http://archive.debian.org/debian/dists/jessie-backports/InRe                                                                                                                                                             lease is expired (invalid since 1035d 9h 20min 39s). Updates for this repository                                                                                                                                                              will not be applied.
finding installer for x86_64
Downloading https://ispyfiles.azureedge.net/downloads/Agent_Linux64_3_7_6_0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.8M  100 27.8M    0     0  6458k      0  0:00:04  0:00:04 --:--:-- 6647k
Archive:  AgentDVR.zip
  inflating: Agent
 extracting: agent-register.sh
 extracting: agent-reset-local-login.sh
 extracting: agent-reset.sh
  inflating: Agent.deps.json
  inflating: Agent.dll
  inflating: Agent.dll.config
  inflating: Agent.runtimeconfig.json
  inflating: AgentDVR.service
   creating: Commands/
 extracting: Commands/Alerts Off.bat
 extracting: Commands/Alerts On.bat
 extracting: Commands/All Off.bat
 extracting: Commands/All On.bat
 extracting: Commands/Apply Schedule.bat
  inflating: Commands/readme.txt
 extracting: Commands/Record Off.bat
 extracting: Commands/Record on Alert.bat
 extracting: Commands/Record on Detect.bat
 extracting: Commands/Restart Agent.bat
 extracting: Commands/Snapshot.bat
 extracting: Commands/Start Record.bat
 extracting: Commands/Stop Cloud Uploads.bat
 extracting: Commands/Stop Record.bat
 extracting: Commands/Stop Streaming.bat
 extracting: Commands/_Example.bat
  inflating: Common.Logging.Core.dll
  inflating: Common.Logging.dll
  inflating: CoreLogic.dll
  inflating: CoreUpdater.dll
  inflating: CoreUpdater.runtimeconfig.json
  inflating: DirectShowLib-2005.dll
  inflating: Emgu.CV.Platform.NetStandard.dll
  inflating: FFmpeg.AutoGen.dll
  inflating: Google.Apis.Auth.dll
  inflating: Google.Apis.Auth.PlatformServices.dll
  inflating: Google.Apis.Core.dll
  inflating: Google.Apis.dll
  inflating: Google.Apis.Drive.v3.dll
  inflating: KoenZomers.OneDrive.Api.dll
  inflating: libcvextern.so
  inflating: libe_sqlite3.so
  inflating: libjingle_peerconnection_so.so
  inflating: libSkiaSharp.so
  inflating: libSystem.IO.Ports.Native.so
  inflating: LibVLCSharp.dll
  inflating: LitJSON.dll
  inflating: Makaretu.Dns.dll
  inflating: Makaretu.Dns.Multicast.dll
   creating: Masks/
  inflating: Masks/demo_mask.png
  inflating: Microsoft.AspNetCore.Connections.Abstractions.dll
  inflating: Microsoft.AspNetCore.Http.Connections.Client.dll
  inflating: Microsoft.AspNetCore.Http.Connections.Common.dll
  inflating: Microsoft.AspNetCore.Http.Features.dll
  inflating: Microsoft.AspNetCore.SignalR.Client.Core.dll
  inflating: Microsoft.AspNetCore.SignalR.Client.dll
  inflating: Microsoft.AspNetCore.SignalR.Common.dll
  inflating: Microsoft.AspNetCore.SignalR.Protocols.Json.dll
  inflating: Microsoft.Extensions.Configuration.Abstractions.dll
  inflating: Microsoft.Extensions.Configuration.Binder.dll
  inflating: Microsoft.Extensions.Configuration.dll
  inflating: Microsoft.Extensions.DependencyInjection.Abstractions.dll
  inflating: Microsoft.Extensions.DependencyInjection.dll
  inflating: Microsoft.Extensions.Logging.Abstractions.dll
  inflating: Microsoft.Extensions.Logging.dll
  inflating: Microsoft.Extensions.Options.dll
  inflating: Microsoft.Extensions.Primitives.dll
  inflating: Microsoft.Win32.Registry.dll
  inflating: Microsoft.Win32.SystemEvents.dll
  inflating: MQTTnet.dll
  inflating: NAudio.Asio.dll
  inflating: NAudio.Core.dll
  inflating: NAudio.dll
  inflating: NAudio.Midi.dll
  inflating: NAudio.Wasapi.dll
  inflating: NAudio.WinForms.dll
  inflating: NAudio.WinMM.dll
  inflating: Newtonsoft.Json.dll
  inflating: OnvifDiscovery.dll
  inflating: Renci.SshNet.dll
  inflating: RtspClientSharp.dll
  inflating: SimpleBase.dll
  inflating: SkiaSharp.dll
   creating: sounds/
  inflating: sounds/airhorn.wav
  inflating: sounds/alarm.wav
  inflating: sounds/alsationxsiberian_bark.wav
  inflating: sounds/alsation_bark.wav
  inflating: sounds/cairnterrierbark.wav
  inflating: sounds/doorbell.wav
  inflating: sounds/police.wav
  inflating: sounds/pop.wav
  inflating: sounds/rottweiler_bark.wav
  inflating: sounds/spanielgrowlbark.wav
  inflating: sounds/wiggle.wav
  inflating: SQLite-net.dll
  inflating: SQLitePCLRaw.batteries_v2.dll
  inflating: SQLitePCLRaw.core.dll
  inflating: SQLitePCLRaw.nativelibrary.dll
  inflating: SQLitePCLRaw.provider.dynamic_cdecl.dll
  inflating: SshNet.Security.Cryptography.dll
  inflating: System.Drawing.Common.dll
  inflating: System.IO.Pipelines.dll
  inflating: System.IO.Ports.dll
  inflating: System.Net.IPNetwork.dll
  inflating: System.Private.ServiceModel.dll
  inflating: System.Reflection.DispatchProxy.dll
  inflating: System.Resources.Extensions.dll
  inflating: System.Security.AccessControl.dll
  inflating: System.Security.Cryptography.Pkcs.dll
  inflating: System.Security.Cryptography.Xml.dll
  inflating: System.Security.Permissions.dll
  inflating: System.Security.Principal.Windows.dll
  inflating: System.ServiceModel.dll
  inflating: System.ServiceModel.Duplex.dll
  inflating: System.ServiceModel.Http.dll
  inflating: System.ServiceModel.NetTcp.dll
  inflating: System.ServiceModel.Primitives.dll
  inflating: System.ServiceModel.Security.dll
  inflating: System.Threading.Channels.dll
  inflating: System.Windows.Extensions.dll
  inflating: Tmds.LibC.dll
  inflating: webrtc.dll
   creating: XML/
  inflating: XML/config.xml
   creating: XML/haarcascades/
  inflating: XML/haarcascades/catface.xml
  inflating: XML/haarcascades/face.xml
  inflating: XML/layouts.xml
  inflating: XML/objects.xml
  inflating: XML/PTZ2.xml
  inflating: XML/Sources.xml
  inflating: XML/Translations.xml
Install dotnet 3.1.300 for Agent (y/n)? y
Yes
Installing dotnet
dotnet-install: Note that the intended use of this script is for Continuous Inte                                                                                                                                                             gration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and wit                                                                                                                                                             hout admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple C                                                                                                                                                             I runs.
dotnet-install: To set up a development environment or to run apps, use installe                                                                                                                                                             rs rather than this script. Visit https://dotnet.microsoft.com/download to get t                                                                                                                                                             he installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/                                                                                                                                                             Sdk/3.1.300/dotnet-sdk-3.1.300-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3                                                                                                                                                             .1.300/dotnet-sdk-3.1.300-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/root/AgentDVR/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
/dev/fd/62: line 82: [: ==: unary operator expected
No default ffmpeg package option - build from source
Build ffmpeg for Agent (y/n)? y
Yes
ffmpeg-build-script v1.33
=========================

Using 8 make jobs simultaneously.
With GPL and non-free codecs
cargo not installed. rav1e encoder will not be available.

building giflib - version 5.2.1
=======================
Downloading https://sourceforge.net/projects/giflib/files/giflib-5.2.1.tar.gz as giflib-5.2.1.tar.gz

Failed to download https://sourceforge.net/projects/giflib/files/giflib-5.2.1.tar.gz. Exitcode 60. Retrying in 10 seconds

Failed to download https://sourceforge.net/projects/giflib/files/giflib-5.2.1.ta                                                                                                                                                             r.gz. Exitcode 60
Found service definition in /etc/systemd/system/AgentDVR.service
Go to http://localhost:8090
root@nas:~# 

**If the install script completed successfully but Agent doesn't start and complains about a file not found**
Change to the Agent DVR directory in terminal and run:

root@nas:~# ./start_agent.sh
Starting...
Creating temp path for opencv in /tmp/
Get com port list
Using default port (8090)
Local Server running on port 8090
H264 compatible version of ffmpeg is required to use H264 encoding. Switch to VP                                                                                                                                                             8 in settings if unable to record.
Accepting connections at http://*:8090/
Access locally at http://192.168.12.230:8090
Agent (v3.7.6.0)
Log start
Process is 64 bit
Using WorkStation GC
Init Webrtc
Init FFmpeg
Looking for ffmpeg in /usr/local/lib
Not in there..
Looking for ffmpeg in /usr/lib/x86_64-linux-gnu
Not in there..
Error: Could not find FFMPEG location. Check the FFMPEG_SEARCH location in confi                                                                                                                                                             g.xml. I need FFMPEG v4 shared libraries like avutil.56
ZeroConf: ZeroConf Service Started
Error:    at CoreLogic.FFmpeg.Init()
   at CoreLogic.Threads.StartUp()
Could not find FFMPEG location. Check the FFMPEG_SEARCH location in config.xml.                                                                                                                                                              I need FFMPEG v4 shared libraries like avutil.56
Install FFMPEG (v4) using the terminal. See the download page on ispyconnect.com                                                                                                                                                              for instructions.
Killed
root@nas:~#

    l

**Comment by ispysoftware** [comment]
can you try 
sudo apt-get install ffmpeg

and say no to build ffmpeg in the setup script

**Comment by djdoubleg** [comment]
Yes, I tried that, too.
Even then, he couldn't find the ffmpeg directory.

**Comment by ispysoftware** [comment]
You could try:
https://www.vultr.com/docs/how-to-install-ffmpeg-on-debian-8-or-9/

**Comment by djdoubleg** [comment]
First try: 
E: Release file for http://www.deb-multimedia.org/dists/jessie/InRelease is expired (invalid since 12d 4h 52min 50s). Updates for this repository will not be applied.
root@nas:~#

Second try with this command:  sudo apt-get -o Acquire::Check-Valid-Until=false update

W: Failed to fetch http://www.deb-multimedia.org/dists/jessie/InRelease  Unable to find expected entry 'non-free/source/Sources' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ispysoftware** [comment]
looks like you might need to upgrade to a newer version of debian.
I tried it this morning on 11 and it worked ok

**Comment by ispysoftware** [comment]
... or do some googling about how to install ffmpeg on debian 8

**Comment by djdoubleg** [comment]
Yes, that would be an easy one.  But it's a NAS that's been working for
several years. Everything that works on it now doesn't work on debian 11.
Virtualbox, OpenMediaVault and many other applications. However, the Docker
version of iPsyconnect is not good because iSpyconnect disappears from the
docker after re-starting the server.

**Comment by ispysoftware** [comment]
i think the build issue you are having with ffmpeg is some SSL related issue

you could try installing:

apt install apt-transport-https

then try building ffmpeg again

**Comment by djdoubleg** [comment]
***@***.***:~# apt install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ispysoftware** [comment]
I dunno then you'll need to dig into why that package won't install on debian 8

**Comment by djdoubleg** [comment]
Thank you!

**Comment by ispysoftware** [comment]
yeah sorry i can't be more help but i can't even install debian 8 here - all the servers the installer is trying to contact for package updates don't even exist any more.

**Comment by ispysoftware** [comment]
for the docker version not persisting issue you need to create volumes - go through
https://github.com/doitandbedone/ispyagentdvr-docker
