### ISSUE TITLE
How to Verify Intel HW h264 encoder / playback is working?

### ISSUE THREAD

**Issue by juanpc2018** [ispysoftware/agent-install-scripts#22]
Encoder: FFMPEG VAAPI
VAAPI Device: Card0: /dev/dri/renderD128
VAAPI Codec: h.264

**Comment by ispysoftware** [comment]
check the logs at /logs.html

**Comment by juanpc2018** [comment]
found 192.168.0.80
ffmpegbase: Camera 1: Found decoder AV_HWDEVICE_TYPE_VAAPI
ffmpegbase: Camera 1: Opening AV_HWDEVICE_TYPE_VAAPI
[AVHWDeviceContext @ 0x7fc584679cc0] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed

ffmpegbase: Camera 1: Using hardware decoder: AV_HWDEVICE_TYPE_VAAPI
ffmpegbase: Camera 2: Found decoder AV_HWDEVICE_TYPE_VAAPI
ffmpegbase: Camera 2: Opening AV_HWDEVICE_TYPE_VAAPI
[AVHWDeviceContext @ 0x7fc56866bec0] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed

ffmpegbase: Camera 2: Using hardware decoder: AV_HWDEVICE_TYPE_VAAPI

same as Konsole.

OBS iHD ffmpeg VAAPI works for Recording,
drivers 2.4.1 installed

AgentDVR also seem to work for Recording:
Opening codec
Using hardware encoder: h264_vaapi
Camera 2: Recording Opened
FrameBuffer: Camera 2: Record stop
Camera 2: Recording Closed


Problem seems Decoding "very high cpu load 50%"

Macmini 2014 8gb

**Comment by ispysoftware** [comment]
It's a driver issue:

https://www.google.com/search?q=dri%2FiHD_drv_video.so+init+failed

**Comment by juanpc2018** [comment]
looking the recorded .mp4 file,
the image moves back & forth, back & forth,
Not smooth forward movement.

OBS records ok.

**Comment by ispysoftware** [comment]
yeah you'll need to check the driver, or record raw if possible. That error is coming from ffmpeg - not something i can fix, and is driver related.

**Comment by juanpc2018** [comment]
$ vainfo
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.12 (libva 2.10.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD

**Comment by ispysoftware** [comment]
**libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1**

**Comment by juanpc2018** [comment]
VAAPI drivers have issues true,
i have fixed the issues...,

Easy to test in Firefox HW decoder
works when installing a "converter" from vaappi to opengl, called vdpau,

very low CPU load when HW Decoder is working.
very High CPU load when CPU Decoder is working.
same YT video.

VLC happens the same...
OpenGL GLX
vs. 
X11 XCB

but intel did Not worked in AgentDVR,
so i decided to install a PNY GT 740 pcie card
using Thunderbolt2 eGpu,
to the MacMini 2014 8GB

Everything works exept AgentDVR,

AgentDVR does Not give errors,
but HW Decoder is Not working...
High CPU load 40%.

------
$ sudo ./start_agent.sh
Starting...
Using default media location
Creating temp path for opencv in /tmp/
Get com port list
Using default port (8090)
Local Server running on port 8090
H264 compatible version of ffmpeg is required to use H264 encoding. Switch to VP8 in settings if unable to record.
Accepting http connections at http://*:8090/
Access locally at http://192.168.0.81:8090
Agent (v4.0.4.0)
Log start
Process is 64 bit 
Using WorkStation GC
Init Webrtc
Init FFmpeg
Looking for ffmpeg in /usr/local/lib
Not in there..
Looking for ffmpeg in /usr/lib/x86_64-linux-gnu
ffmpeg path: /usr/lib/x86_64-linux-gnu
Initializing devices
vdpau
ZeroConf: ZeroConf Service Started
cuda
vaapi
qsv
drm
opencl
Found 0 devices
call arecord -l
Preloading Images
Turn Server accepting connections at 192.168.0.81:3478 using range 50000-50010)
MQTT not configured or enabled
Loaded 2 cameras and 2 mics from /home/mama/AgentDVR/Media/XML/objects.xml
Running at http://localhost:8090
IP addresses:
192.168.0.81
Enable: Camera 2: Enabled
Enable: Camera 1: Enabled
Enable: Camera 1 mic: Start audio
Enable: Camera 2 mic: Start audio
Enable: Camera 2 mic: Enabled
Enable: Camera 1 mic: Enabled
found 192.168.0.xxx

TURN: Welcome user
TURN: Welcome user
TURN: Welcome user
TURN: Welcome user
TURN: Welcome user
TURN: Welcome user
TURN: Welcome user
TURN: Welcome user
TURN: Welcome user
TURN: Welcome user
rtc:added servers
rtc:inited peer connection (True)
rtc:set flag
rtc:onsuccessanswer
ICE state: Connected
rtc:ondatachannelstatechange (serverdata: Open)
rtc: opened serverdata
rtc:ondatachannelstatechange (talk: Open)
rtc: opened talk
ffmpegbase: Camera 1: Found decoder AV_HWDEVICE_TYPE_CUDA
ffmpegbase: Camera 1: Opening AV_HWDEVICE_TYPE_CUDA
ffmpegbase: Camera 2: Found decoder AV_HWDEVICE_TYPE_CUDA
ffmpegbase: Camera 2: Opening AV_HWDEVICE_TYPE_CUDA
ffmpegbase: Camera 2: Using hardware decoder: AV_HWDEVICE_TYPE_CUDA
ffmpegbase: Camera 1: Using hardware decoder: AV_HWDEVICE_TYPE_CUDA

**Comment by juanpc2018** [comment]
VLC rtsp Player does Not work,
rtsp is broken in Linux 3.0.16 Vetinari when installed from Kubuntu repo with Synaptic.
works when installed from Snap

VLC OpenGL GLX HW Decoder acceleration works ok.

there is an alternative player:
rtspplayer.com
works in full screen.
but has some issues with window mode.

i dont remember if has sound,

---------

[00007f248011c0f0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[00007f246c0a9940] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
found 192.168.0.100
found 192.168.0.101
vlc started
vlc started
[00007f2450001690] satip stream error: Failed to setup RTSP session
[00007f245c001690] satip stream error: Failed to setup RTSP session
[00007f248013a530] main input error: Your input can't be opened
[00007f248013a530] main input error: VLC is unable to open the MRL 'rtsp://username:password@192.168.0.100/stream1'. Check the log for details.
Error: SourceError: Camera 1: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 1 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped
SourcePlayingFinished: Camera 1: Playing finished (SourceError)
Reconnect: Camera 1: Reconnecting in 2s
[00007f246c0b91c0] main input error: Your input can't be opened
[00007f246c0b91c0] main input error: VLC is unable to open the MRL 'rtsp://username:password@192.168.0.101/stream1'. Check the log for details.
Error: SourceError: Camera 2: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 2 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped
SourcePlayingFinished: Camera 2: Playing finished (SourceError)
Reconnect: Camera 2: Reconnecting in 2s
found 192.168.0.88
intervals: Camera 2: Reconnecting
intervals: Camera 1: Reconnecting
vlc start
vlc start
intervals: Camera 1: Reconnect Exit
intervals: Camera 2: Reconnect Exit
[00007f246c0a9940] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[00007f2458019df0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
vlc started
vlc started
[00007f245c001100] satip stream error: Failed to setup RTSP session
[00007f2450002040] satip stream error: Failed to setup RTSP session
[00007f246c0e71a0] main input error: Your input can't be opened
[00007f246c0e71a0] main input error: VLC is unable to open the MRL 'rtsp://username:password@192.168.0.101/stream1'. Check the log for details.
Error: SourceError: Camera 2: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 2 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped
SourcePlayingFinished: Camera 2: Playing finished (SourceError)
Reconnect: Camera 2: Reconnecting in 5s
[00007f2458023a90] main input error: Your input can't be opened
[00007f2458023a90] main input error: VLC is unable to open the MRL 'rtsp://username:password@192.168.0.100/stream1'. Check the log for details.
Error: SourceError: Camera 1: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 1 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped

**Comment by juanpc2018** [comment]
i removed VLC
and installed from Snap..
https://snapcraft.io/vlc
$ sudo snap install vlc --edge

Opera fixes some issues.
VLC too.

VLC 4.0.0-dev Otto 
rtsp works now, 
but Not with AgentDVR


vlc started
vlc started
Error: SourceError: Camera 2: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 2 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped
Error: SourceError: Camera 1: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 1 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped
SourcePlayingFinished: Camera 1: Playing finished (SourceError)
SourcePlayingFinished: Camera 2: Playing finished (SourceError)

lc started
Error: SourceError: Camera 1: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 2: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 1 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 2 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped

**Comment by juanpc2018** [comment]
Decoder NONE
has 12% CPU load.

**Comment by juanpc2018** [comment]
VLC 3.0.16 installed from Snap, rtsp works.
but....
same error...

Initialized VLC
vlc started
Error: SourceError: Camera 1: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 1 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped
SourcePlayingFinished: Camera 1: Playing finished (SourceError)
Reconnect: Camera 1: Reconnecting in 2s
intervals: Camera 1: Reconnecting
vlc start
intervals: Camera 1: Reconnect Exit
vlc started
Error: SourceError: Camera 1: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 1 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped
SourcePlayingFinished: Camera 1: Playing finished (SourceError)
Reconnect: Camera 1: Reconnecting in 5s
intervals: Camera 1: Reconnecting
vlc start
intervals: Camera 1: Reconnect Exit
vlc started
Error: SourceError: Camera 1: CoreLogic.Sources.Combined.VlcStream:Source Error
Error: SourceError: Camera 1 mic: CoreLogic.Sources.Combined.VlcStream:Source Error
VLC stopped
SourcePlayingFinished: Camera 1: Playing finished (SourceError)
Reconnect: Camera 1: Reconnecting in 10s

**Comment by juanpc2018** [comment]
there is an error in AgentDVR,
i think i need to recompile again.

**Comment by ispysoftware** [comment]
It's a driver issue:

https://www.google.com/search?q=dri%2FiHD_drv_video.so+init+failed
