### ISSUE TITLE
Bug: Camera TimeStamp Show Background Switch is Inverted On = Hide.

### ISSUE THREAD

**Issue by juanpc2018** [ispysoftware/agent-install-scripts#24]
Kubuntu 21.10
Konkeror Browser.
Agent v4.0.4.0

**Comment by ispysoftware** [comment]
I'm not seeing this - on = show, off = hide on my computer - screenshots?

**Comment by juanpc2018** [comment]
maybe we have a communication problem,
like Trackpad Natural Scroll setting...

i mean: when the Switch is On/Active, displays a Dark Background around Timestamp text.
i think it should be opposite: when Switch is Active/On, Timestamp Background becomes Transparent.

**Comment by ispysoftware** [comment]
yeah on = show background, as in display a background under the text, off = don't
