### ISSUE TITLE
Request: Timestamp Font Halo & Shadow.

### ISSUE THREAD

**Issue by juanpc2018** [ispysoftware/agent-install-scripts#25]
Font has Color,
Solid Background,
Transparent Background,

Agent lacks Halo & Shadow Font.

Halo & Shadow colors should be Different than Font and Background Color.

double Font, like Matryoshka Russian Dolls = Halo.
or same size Shadow.

**Comment by ispysoftware** [comment]
will be in next update - outline option on timestamp
