### ISSUE TITLE
Font Not Found After Update.

### ISSUE THREAD

**Issue by engineerisaac** [ispysoftware/agent-install-scripts#26]
Ran the Latest Update via web portal v4.0.9.0

Resulted in Crashed Server:

nvr@nvr:~$ ./start_agent.sh
Error:
  An assembly specified in the application dependencies manifest (Agent.deps.json) was not found:
    package: 'SixLabors.Fonts', version: '1.0.0-beta15'
    path: 'lib/netstandard2.1/SixLabors.Fonts.dll'
nvr@nvr:~$

**Comment by ispysoftware** [comment]
sorry didnt see this - are you still having this issue?
