### ISSUE TITLE
Aborted core dumped

### ISSUE THREAD

**Issue by pepoangel** [ispysoftware/agent-install-scripts#27]
Starting...
Using default media location
Creating temp path for opencv in /tmp/
Get com port list
Using default port (8090)
Local Server running on port 8090
No usable version of libssl was found
Aborted (core dumped)

systemctl status AgentDVR.service 
● AgentDVR.service - AgentDVR
     Loaded: loaded (/etc/systemd/system/AgentDVR.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2022-07-21 18:25:54 AST; 2s ago
    Process: 9879 ExecStart=/home/pepo/start_agent.sh (code=exited, status=134)
   Main PID: 9879 (code=exited, status=134)
        CPU: 322ms

**Comment by ispysoftware** [comment]
take a look at 

https://www.reddit.com/r/ispyconnect/comments/ucbcsq/starting_agentdvr_on_ubuntu_2204_jammy_fails_due/
