### ISSUE TITLE
request info

### ISSUE THREAD

**Issue by tammeryousef1006** [ispysoftware/agent-install-scripts#29]
For issues with AgentDVR itself please use the [Reddit Forum](https://www.reddit.com/r/ispyconnect/) - This repo is for issues with installing and starting Agent DVR.
what is the live url to view at vlc or web page or through other browser on same network ? 
i tired the mjpeg url that provided below but not working 
MJPEG Video Feeds

http://IPADDRESS:8080/mjpegfeed?oid=CAM_ID&full : full size movie
http://IPADDRESS:8080/mjpegfeed?oid=CAM_ID&thumb : thumbnail movie
http://IPADDRESS:8080/mjpegfeed?oid=CAM_ID&size=640x480 : resized movie

**Comment by ispysoftware** [comment]
you're looking at the wrong api page
https://www.ispyconnect.com/userguide-agent-api.aspx

video.mjpg?group=home&size=320x240&cycle=4 : return an mjpeg live feed of cameras in the group "home", cycling between them every 4 seconds
