### ISSUE TITLE
Agent DVR 4.1.3.0

### ISSUE THREAD

**Issue by victor7376** [ispysoftware/agent-install-scripts#30]
I noticed there was an update today for Agent DVR, I did two tries of the install & also the download (manually) for version 4.1.3.0, but after restarting & also stop / start the software on Ubuntu is still stating its on 4.1.1.0.

This is even after downloading the Agent_Linux64_4_1_3_0.zip file & overwriting.

**Comment by ispysoftware** [comment]
you'll need to run Agent from the terminal window and check the output, i'm guessing the original version is running somewhere else and using the local 8090 port.

**Comment by victor7376** [comment]
I’ve got 2 servers, one is the main cctv and the 2nd is the test one.  I normally run the download script to download the latest version when it’s been released and extract the files over the top of the AgentDVR folder.  It has been working perfectly like this up to now.

Running the download script only downloads version 4.1.1.0, running the Linux install script installs version 4.1.2.0 if there’s no Agentdvr folder there.  But as soon as I run Agentdvr it states there’s a new version (4.1.3.0), so I decided to manually download the 4.1.3.0 Linus zip file which I was able to do, then extracted the contents to the Agentdvr (both over the top of the 4.1.1.0 & 4.1.2.0 on two test servers) and they still report as being version 4.1.1.0 (which 4.1.2.0 reverts back to 4.1.1.0).  I even tried stopping Agentdvr as a service extracting the new version and overwriting then starting the service up again, but still reports as 4.1.1.0.


This is the first time I’ve had an issue with updating.

**Comment by ispysoftware** [comment]
The original download script is capped at 4.1.1.0 - as explained in the update logs
The new download script
https://github.com/ispysoftware/agent-install-scripts/tree/main/v2/install.sh
will download and install the new version

you can download the installer new version file here
https://ispyfiles.azureedge.net/downloads/Agent_Linux64_4_1_3_0.zip

I just tested it here, works fine

![image](https://user-images.githubusercontent.com/800093/186138078-ca4e8503-726d-4020-9ba2-d77d6452567c.png)


The only way you'll end up with 4.1.1.0 is if it's in use - recommend stopping the service and deleting it first

**Comment by victor7376** [comment]
Well I ran the command and Agentdvr won’t start now with exit code 131.

I can start it manually using the start_agent.sh

but the service command wont work.

I tried on the test server and it did the same thing and was only able to get it to work by deleting Agentdvr folder and uninstalling it, then reinstalling it with the above command you gave.

But the main server I have a lot of recordings and settings I don’t want to loose.

**Comment by ispysoftware** [comment]
yeah you need to run the install script. If you have problems you'll need to log a ticket with the output from the install script along with the startup output and what OS you are using.

for the main server just don't delete the media folder.

**Comment by victor7376** [comment]
Why did you close the issue??

Backing up the media folder will take 3-5 hours, I believe the issue is because of dotnet.  I believe you're sing dotnet3.1 which Ubuntu 22.04 which has just recently upgraded uses dotnet6.

I've had to rename Agentdvr to Agentdvr_old, run uninstall.sh - then used the install.sh to reinstall the application.  Then restore the configs for the program to actually work.  But all the old recordings are still on the old version which I cant see how to import them into the net install.

This is what was showing:

● AgentDVR.service - AgentDVR
     Loaded: loaded (/etc/systemd/system/AgentDVR.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-08-23 13:38:14 BST; 3s ago
    Process: 84972 ExecStart=/home/username/AgentDVR/Agent (code=exited, status=150)
   Main PID: 84972 (code=exited, status=150)
        CPU: 3ms

Aug 23 13:38:24 username-LINUX AgentDVR[84978]: You must install or update .NET to run this application.
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: App: /home/username/AgentDVR/Agent
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: Architecture: x64
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: Framework: 'Microsoft.NETCore.App', version '3.1.0' (x64)
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: .NET location: /usr/lib/dotnet/dotnet6-6.0.108
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: No frameworks were found.
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: Learn about framework resolution:
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: https://aka.ms/dotnet/app-launch-failed
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: To install missing framework, download:
Aug 23 13:38:24 username-LINUX AgentDVR[84978]: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.22.04-x64
Aug 23 13:38:24 username-LINUX systemd[1]: AgentDVR.service: Failed with result 'exit-code'.

**Comment by ispysoftware** [comment]
i closed it because it's not an issue with the install script. An issue with the install script looks like  output from the script install command describing an error.

This is an issue with you updating your version of Agent by not using the install script.

It says on the update logs:
https://www.ispyconnect.com/producthistory.aspx?productid=27

Agent DVR
Important!
If you are on version 4.1.1.0 or below and are running Linux or OSX or Docker then you will need to run the installer from the [download page](https://www.ispyconnect.com/download.aspx) to update (due to an FFmpeg version bump). Running an update on these platforms will just reinstall v4.1.1.0


The install script will fix the issue with the service file. Unzipping the package isn't enough to update it.

Your service file is calling dotnet on the new executable which doesn't use that framework anymore. This is why it's not working.
It just needs to call the new executable directly (which is using net 6)

You need to read the update instructions.

You don't need to move the media directory - just delete the dll's and libraries from the Agent directory (or copy them somewhere in case you have problems) and run the install script to install the new version in the same place.
