### ISSUE TITLE
Linux Agent Update

### ISSUE THREAD

**Issue by everyonelovespepsicola** [ispysoftware/agent-install-scripts#31]
followed the directions to update on linux but then i had to start over and set everything back up

**Comment by ispysoftware** [comment]
doesn't give us a lot to work with - which linux, what happened, errors etc?

**Comment by everyonelovespepsicola** [comment]
am i supposed run the install script again on top to the original install, or is there a update script that i run?

**Comment by ispysoftware** [comment]
have a read of
https://github.com/ispysoftware/agent-install-scripts

the readme explains how to update by downloading the latest files for your platform

you'd need to stop the service, update it and then start it again
