### ISSUE TITLE
How do I uninstall on Linux?

### ISSUE THREAD

**Issue by jkemp814** [ispysoftware/agent-install-scripts#32]
**Describe the bug**
A clear and concise description of what the bug is. For issues with Agent DVR itself please use the [Reddit Forum](https://www.reddit.com/r/ispyconnect/) - This repo is for issues with installing and starting Agent DVR.

**Information**
- OS Fedora Linux 37 Silverblue
- OS 37 Silverblue
- 64 bit

**Console output from installer**
Please paste the output from the installer showing the error messages

**If the install script completed successfully but Agent doesn't start and complains about a file not found**
Change to the Agent DVR directory in terminal and run:

    ldd libcvextern.so (or whatever library is causing issues). 

The output should tell you which dependencies need to be installed.  Try installing these dependencies using (replace xxxx with the missing dependency name):

    sudo apt-get install xxxx

.. and update this report with the missing libraries.

If that doesn't resolve the issue start agent by calling:

LD_DEBUG=libs ./start_agent.sh

and attach the output to this ticket

**Additional context**

How do I uninstall on Linux. Fedora Linux 37 Silverblue comes with Podman. Will the docker version install using it instead? I also have FFmpeg version 5.1.1 installed inside the same toolbox, but the software complains it cannot find it. Please help. Would like to get this going on this system.

Thank you,
james

**Comment by ispysoftware** [comment]
https://www.ispyconnect.com/userguide-agent-DVR.aspx#uninstalling

you need ffmpeg shared build not static - it needs the ffmpeg shared binaries under any of the following

"ffmpeg-v5/workspace/lib", "/usr/local/lib", "/usr/lib/x86_64-linux-gnu", "/usr/lib/{platform}-linux-gnueabi", "/usr/lib/x86_64-linux-gnueabihf"
