### ISSUE TITLE
Installation fails - ./Agent: No such file or directory

### ISSUE THREAD

**Issue by runegang** [ispysoftware/agent-install-scripts#33]
**Describe the bug**
Can't install the system through the script. Has tried on multiple Ubuntu versions including a full VM without any success.
Complains about missing ./Agent.

**Information**
- OS name - Ubuntu 20.04 on Proxmox LXC
- OS version 20.04
- 32 bit or 64 bit - 64Bit

**Console output from installer**
chmod: cannot access './Agent': No such file or directory

**If the install script completed successfully but Agent doesn't start and complains about a file not found**

LD_DEBUG=libs ./start_agent.sh
      4977:     find library=libtinfo.so.6 [0]; searching
      4977:      search cache=/etc/ld.so.cache
      4977:       trying file=/lib/x86_64-linux-gnu/libtinfo.so.6
      4977:
      4977:     find library=libdl.so.2 [0]; searching
      4977:      search cache=/etc/ld.so.cache
      4977:       trying file=/lib/x86_64-linux-gnu/libdl.so.2
      4977:
      4977:     find library=libc.so.6 [0]; searching
      4977:      search cache=/etc/ld.so.cache
      4977:       trying file=/lib/x86_64-linux-gnu/libc.so.6
      4977:
      4977:
      4977:     calling init: /lib/x86_64-linux-gnu/libc.so.6
      4977:
      4977:
      4977:     calling init: /lib/x86_64-linux-gnu/libdl.so.2
      4977:
      4977:
      4977:     calling init: /lib/x86_64-linux-gnu/libtinfo.so.6
      4977:
      4977:
      4977:     initialize program: /bin/bash
      4977:
      4977:
      4977:     transferring control: /bin/bash
      4977:
./start_agent.sh: line 5: ./Agent: No such file or directory
      4978:
      4978:     calling fini: /bin/bash [0]
      4978:
      4978:
      4978:     calling fini: /lib/x86_64-linux-gnu/libtinfo.so.6 [0]
      4978:
      4978:
      4978:     calling fini: /lib/x86_64-linux-gnu/libdl.so.2 [0]
      4978:
      4977:
      4977:     calling fini: /bin/bash [0]
      4977:
      4977:
      4977:     calling fini: /lib/x86_64-linux-gnu/libtinfo.so.6 [0]
      4977:
      4977:
      4977:     calling fini: /lib/x86_64-linux-gnu/libdl.so.2 [0]
      4977:

**Additional context**

**Comment by ispysoftware** [comment]
do you have the output from the install script?
does a file called Agent exist in the AgentDVR folder?

**Comment by ispysoftware** [comment]
.. just ran 
bash <(curl -s "https://raw.githubusercontent.com/ispysoftware/agent-install-scripts/main/v2/install.sh")

here on a new ubuntu VM on windows, worked fine..

**Comment by hexyncode** [comment]
It might be worth checking, as I originally had this issue.

When installing a fresh copy of Ubuntu Server 22.10 (32-bit) onto my Raspberry Pi, it doesn't come with the unzip command preinstalled.

Fixable by a standard `sudo apt install zip unzip` and then ran it again - now fully works.

**Comment by ispysoftware** [comment]
Thanks, will update
