### ISSUE TITLE
Ubuntu curl install problem while attempt to get Agent_Linux64_4_5_8_0.zip

### ISSUE THREAD

**Issue by starman2021** [ispysoftware/agent-install-scripts#36]
On Ubuntu curl install - there is an issue downloading "AgentDVR.zip".   The relevant output of the curl install is:

```
finding installer for x86_64
Downloading
curl: (3) <url> malformed
unzip:  cannot find or open AgentDVR.zip, AgentDVR.zip.zip or AgentDVR.zip.ZIP.
rm: cannot remove 'AgentDVR.zip': No such file or directory

```
For my system, the bash commands are:

```
purl="https://www.ispyconnect.com/api/Agent/DownloadLocation4?platform=Linux64&fromVersion=0"

AGENTURL=$(curl -s --fail "$purl" | tr -d '"')
echo "Downloading $AGENTURL"
curl --show-error --location "$AGENTURL" -o "AgentDVR.zip"
unzip `AgentDVR.zip
```
        

I was able to work around with :

`wget https://ispyfiles.azureedge.net/downloads/Agent_Linux64_4_5_8_0.zip`

Then unzip within the AgentDVR directory, chmod +x Agent and run Agent. 
Port 8090 is serving content.

**Comment by ispysoftware** [comment]
i'm guessing there was an issue with the script getting the download location. Are you still seeing the same thing?

**Comment by klcampbell6502** [comment]
I'm seeing exactly the same error on a fresh Ubuntu install

**Comment by ispysoftware** [comment]
what do you see when you run 
echo $(curl "https://www.ispyconnect.com/api/Agent/DownloadLocation4?platform=Linux64&fromVersion=0" | tr -d '"')

from the terminal? 

I get:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    69  100    69    0     0     41      0  0:00:01  0:00:01 --:--:--    41
https://ispyfiles.azureedge.net/downloads/Agent_Linux64_4_6_0_0.zip

**Comment by klcampbell6502** [comment]
It just echoes the URL:

kevin@ukdvr:~$ echo $(curl -s --fail "https://www.ispyconnect.com/api/Agent/DownloadLocation4?platform=Linux64&fromVersion=0" | tr -d '"')
https://ispyfiles.azureedge.net/downloads/Agent_Linux64_4_6_0_0.zip
kevin@ukdvr:~$

**Comment by klcampbell6502** [comment]
Sorry about the strikeout, apparently pasting embedded some sort of command code

**Comment by ispysoftware** [comment]
hmm should work then, unless the script doesn't have permission to access the network for some reason -  or possibly the webserver was having some temporary issue

**Comment by klcampbell6502** [comment]
Using wget worked fine, FWIW.

**Comment by ispysoftware** [comment]
hmm weird - working fine here - if anyone else has this issue then run 

    echo $(curl "https://www.ispyconnect.com/api/Agent/DownloadLocation4?platform=Linux64&fromVersion=0" | tr -d '"')

..and paste in the output here

**Comment by klcampbell6502** [comment]
If I simply use curl without the _echo $(_ it works as expected, which perhaps makes sense since that's what echo does?

Not a *nix expert by any means here ...

**Comment by ispysoftware** [comment]
yeah that's just to dump the response to the console so i can see what the problem is
