### ISSUE TITLE
Start problem on raspberry pi 5

### ISSUE THREAD

**Issue by rolarndt** [ispysoftware/agent-install-scripts#39]
**Describe the bug**
At installing the Agent DVR on a raspberry pi 5 (4GB) I got the following error messages (see below). I'm a real beginner, so I dont understand what it means an cannot get behind. Can you help me?

**Information**
- OS PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- 64 bit

**Console output from installer**
Agent (v5.1.4.0)
Starting...
Detected: LinuxARM64
Creating temp path for opencv in /tmp/
Get com port list
Conf: Check /home/pi/AgentDVR/Media/WebServerRoot/Media/
Using WorkStation GC
StartUp: Inbuilt SOAP auth unavailable (using alternate)
Using Original WebRTC library
Init FFmpeg
ffmpeg6/lib not found
ffmpeg-v6/workspace/lib not found
Checking in /usr/local/lib
Checking in /usr/lib/aarch64-linux-gnu
/usr/lib/aarch64-linux-gnueabi not found
/usr/lib/aarch64-linux-gnueabihf not found
Installing FFmpeg6
StartUp: P2P library not installed (this is normal)
Init: NDI
Downloading https://ispyrtcdata.blob.core.windows.net/downloads/ffmpeg6-linuxarm64.tar.xz
Init SDL
StartUp: SDL not available (SDL not available on all platforms - local talk playback disabled)
Database
Preloading Images
Unhandled exception. System.TypeInitializationException: The type initializer for 'Pixiv.Rtc.ThreadManager' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'jingle_peerconnection_so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libjingle_peerconnection_so: cannot open shared object file: No such file or directory
   at Pixiv.Rtc.ThreadManager.rtcThreadManagerInstance()
   at Pixiv.Rtc.ThreadManager..cctor()
   --- End of inner exception stack trace ---
   at Pixiv.Rtc.ThreadManager.get_Instance()
   at CoreLogic.Server.WebRTC.RTCConnection.RunTURN()
   at System.Threading.Thread.StartCallback()
/dev/fd/62: Zeile 121:  4877 Abgebrochen             ./Agent

**Comment by 0llifreak** [comment]
I get the same error message on a Raspberry Pi 5 (8 GB RAM, 64-bit).

**Comment by ispysoftware** [comment]
On OSX, Linux, or Raspberry Pi, missing libraries can cause start-up failures (like a missing 'libcvextern.so'). Use commands like 'ldd' or 'objdump -r --dylibs-used' to identify and install missing dependencies. 

Some linux distro's have missing pieces that Agent needs - we primarily test on Ubuntu - or you can use the docker version

**Comment by 0llifreak** [comment]
> Some linux distro's have missing pieces that Agent needs - we primarily test on Ubuntu - or you can use the docker version

I use the Docker version on the Raspberry Pi and still get this error message.

**Comment by ispysoftware** [comment]
you'd need to log an issue on the github repo for the docker container
along with as many logs / output as you can find

**Comment by Tango77C** [comment]
So can we take this as a final statement there is no support for a Raspberry Pi deployment?

**Comment by ispysoftware** [comment]
@Tango77C no - works fine on my raspberry pi 4b. It depends what OS you have installed on it. Some pi os's are missing dependencies. Put ubuntu on it.
