### ISSUE TITLE
libcvextern.so and 

### ISSUE THREAD

**Issue by RichardBeisser** [ispysoftware/agent-install-scripts#5]
Hello,

I installed AgentDVR on an rPI4 Raspian Bullseye using your script:
bash <(curl -s "https://raw.githubusercontent.com/ispysoftware/agent-install-scripts/main/install.sh")

After installation, there are 2 errors in journald:
dotnet: File /root/AgentDVR/libcvextern.so cannot 
dotnet: File /root/AgentDVR/libopencv_videoio_ffmpeg430_64.so do not exist.

In your Userguide you wrote:
On Linux and Raspberry Pi your system may not have some required libraries installed and Agent may fail to start with an error like libcvextern.so could not be found. You will need to use ldd to find which libraries are missing. To do this, open a terminal window, change to the Agent directory and run ldd libcvextern.so (or whatever library is causing issues). The output should tell you which dependencies need to be installed. Please let us know what's needed and what operating system you are using so we can update our docs.

I dont understand this.

result of ldd libcvextern.so:
`        linux-vdso.so.1 (0xbeceb000)
        libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb59a6000)
        liblapack.so.3 => /usr/lib/arm-linux-gnueabihf/liblapack.so.3 (0xb5412000)
        libcblas.so.3 => /usr/lib/arm-linux-gnueabihf/libcblas.so.3 (0xb53e6000)
        libatlas.so.3 => /usr/lib/arm-linux-gnueabihf/libatlas.so.3 (0xb5114000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb5100000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb50d4000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb50bc000)
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb4f34000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb4ec5000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb4e98000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb4d44000)
        /lib/ld-linux-armhf.so.3 (0xb6f1d000)
        libblas.so.3 => /usr/lib/arm-linux-gnueabihf/libblas.so.3 (0xb4d01000)
        libgfortran.so.5 => /usr/lib/arm-linux-gnueabihf/libgfortran.so.5 (0xb4c11000)
`
how does this help me??

result of ldd libopencv_videoio_ffmpeg430_64.so:
file not found.

??????

**Comment by ispysoftware** [comment]
"dotnet: File /root/AgentDVR/libcvextern.so cannot"... cannot what?
you might need to run 
dotnet Agent.dll 
in terminal and get the error message there

**Comment by RichardBeisser** [comment]
> "dotnet: File /root/AgentDVR/libcvextern.so cannot"... cannot what? you might need to run dotnet Agent.dll in terminal and get the error message there

ups, sorry, copy and paste error from myside

dotnet: File /root/AgentDVR/libcvextern.so cannot be loaded.
and
dotnet: File /root/AgentDVR/libopencv_videoio_ffmpeg430_64.so do not exist.

I installed the systemd-Service which the install-script offers.
There is no difference between running as service and  starting in a terminal.

Because the file /root/AgentDVR/libcvextern.so existes, i can run the command "ldd libcvextern.so" described in the userguide. The result I posted above.
But I dont know how this result can help me to solve the problem with the message 
/root/AgentDVR/libcvextern.so cannot be loaded

Because the file /root/AgentDVR/libopencv_videoio_ffmpeg430_64.so doesnt exist, I cannot run a ldd-command on that file.

**Comment by ispysoftware** [comment]
libopencv_videoio_ffmpeg430_64.so is not used by Agent - it's not a problem it's not there

usually ldd says that something is missing or not found - in this case it looks like it's finding everything which usually means a dependency of one of those libraries is missing.

in that case you can use ld_debug to dump out what it's trying to find:

http://www.bnikolic.co.uk/blog/linux-ld-debug.html
