### ISSUE TITLE
how can i remove AgentDVR on my raspberry?

### ISSUE THREAD

**Issue by avunculo** [ispysoftware/agent-install-scripts#8]
how can i remove AgentDVR on my raspberry?

**Comment by ispysoftware** [comment]
just delete the folder

**Comment by PrakharVasishtha** [comment]
which folder? can you please elaborate, why is it made so cryptic to uninstall it?

**Comment by ispysoftware** [comment]
@PrakharVasishtha  cryptic? just delete the folder you installed it to.
i've got no idea where you installed it - possibly on your desktop? wherever you ran the setup script.
