### ISSUE TITLE
Error: Media directory could not be found (/agent/Media/WebServerRoot/Media/)

### ISSUE THREAD

**Issue by pumucklll** [ispysoftware/agent-install-scripts#9]
Hello,

**Describe the bug**

Error: Media directory could not be found (/agent/Media/WebServerRoot/Media/)
![image](https://user-images.githubusercontent.com/47299110/153425774-a8a1432e-9dbb-461a-a6fa-35c8d5cac750.png)

the Main folder is : ~/AgentDVR and not  /agent

![image](https://user-images.githubusercontent.com/47299110/153426079-9c54c6d0-b0bc-4b72-af69-da02b6ab613f.png)

For me it lookslike the installscript is wrong.

**Information**
-Vm ware VM  Ubutu server 20.4  64 bit

LD_DEBUG=libs ./start_agent.sh

[LD_DEBUG=libs start_agent sh.txt](https://github.com/ispysoftware/agent-install-scripts/files/8041724/LD_DEBUG.libs.start_agent.sh.txt)

**Comment by ispysoftware** [comment]
issue was with loading old config
